###################################### HELLO! ###########################################################
# This script links functional annotations produced by ResFinder (ARG detection) with taxonomic annotations generated by Kraken2 at the read level.
# ------------
# Input
# ------------
# 1) ResFinder (KMA) output
#   One subdirectory per sample, each containing:
#
#    resfinder_kma/
#      - kma_*.frag.gz : read-level alignments (KMA fragment files)
#      - kma_*.res     : template-level summary statistics (coverage, identity, etc.)
# 2) Kraken2 reports
#   One Kraken2 mapping file per sample containing read-level taxonomic assignments.
# -----------
# Steps 
# -----------
# 1) Gene-level filtering :
#   coverage and identity thresholds based on the corresponding *.res files
#   (default: coverage ≥ 60%, identity ≥ 80%). !!!Please adapt this params depending on your data and scientific question!!!
#
# 2) Read-level ARG assignment
#   For each read, only hits mapping to validated genes are considered.
#   When a read maps to multiple genes, the gene with the highest KMA bit score is selected. 
#   Reads with unresolved multi-gene assignments are not retained.
#
# 3) Taxonomic mapping
#   Reads are matched to species-level taxonomic assignments using Kraken2 mapping files.
#
# 4) Species–ARG association
#   For each sample, species and ARG assignments are combined to generate species–ARG pairs. 
#   Gene counts are computed per sample and aggregated into a sample-by-gene matrix.
# ---------
# Outputs
# ---------
# 1) Species–ARG association table (CSV)
#    A two-column table containing:
#      - Sample: sample identifier
#      - Species_ARG: concatenated species and ARG identifier
############################################################################################################

import os
import gzip
import argparse
from collections import defaultdict, Counter

# ----------------------------------------------
# formating  reports, filtering and read count 
# ----------------------------------------------

def initialize_csv(csv_output):
    if not os.path.exists(csv_output):
        with open(csv_output, "w") as f:
            f.write("Sample,Species_ARG,Count\n")

def filter_genes(res_file, cov_threshold, id_threshold):
    # Filter genes from .res file based on coverage and identity thresholds
    gene_quality = {}
    with open(res_file) as f:
        for line in f:
            if line.startswith('#'): continue
            parts = line.split()
            try:
                if float(parts[5]) >= cov_threshold and float(parts[4]) >= id_threshold:
                    gene_quality[parts[0]] = None
            except (IndexError, ValueError):
                continue
    return gene_quality

def normalize_read_id(read_id):
    # Normalize read ID 
    return read_id.split()[0]

def process_frag_file(frag_file, valid_genes, temp_dir):
    # Process .frag.gz file and select best hit per read if unambiguous
    out = os.path.join(temp_dir, os.path.basename(frag_file) + ".filtered.txt")
    best = {}
    multi = set()
    with gzip.open(frag_file, "rt") as f:
        for line in f:
            parts = line.rstrip().split("\t")
            if len(parts) < 7 or parts[5] not in valid_genes:
                continue
            try:
                score = float(parts[2])
            except ValueError:
                continue
            read_id = normalize_read_id(parts[6])
            if read_id in best:
                if score > best[read_id][1]:
                    best[read_id] = (parts[5], score)
                multi.add(read_id)
            else:
                best[read_id] = (parts[5], score)
    with open(out, "w") as f:
        for r, (g, _) in best.items():
            if r not in multi:
                f.write(f"{r}\t{g}\n")
    return out

def process_sample_step1(sample_id, resfinder_dir, cov, identity, temp_dir):
    # For a given sample, filter genes and reads with valid gene hits
    sample_path = os.path.join(resfinder_dir, sample_id, "resfinder_kma")
    valid_genes = {}
    for f in os.listdir(sample_path):
        if f.endswith(".res"):
            valid_genes.update(filter_genes(os.path.join(sample_path, f), cov, identity))
    temp_files = [
        process_frag_file(os.path.join(sample_path, f), valid_genes, temp_dir)
        for f in os.listdir(sample_path) if f.endswith(".frag.gz")
    ]
    return temp_files, valid_genes

def process_kraken_file(kraken_file):
    # Parse Kraken output and map read_id to species (genus_species or TaxID format)
    taxonomy = {}
    with open(kraken_file) as f:
        for line in f:
            parts = line.rstrip().split("\t")
            if len(parts) >= 4:
                taxonomy[parts[1]] = f"{parts[2]}_{parts[3]}"    # here you can adapt depending on the format of the kraken report (TaxID or Genus_species)
    return taxonomy

def mapping_with_kraken(sample_id, temp_files, valid_genes, kraken_dir, csv_output):
    # Map reads to species using Kraken, then count unique species_ARG pairs per sample
    taxonomy = process_kraken_file(os.path.join(kraken_dir, f"{sample_id}_R1_trimmed_nohost.kraken"))
    pair_counter = Counter()
    for tf in temp_files:
        with open(tf) as f:
            for line in f:
                read_id, gene = line.rstrip().split("\t")
                species = taxonomy.get(read_id)
                if species:
                    pair = f"{species}_{gene}"
                    pair_counter[pair] += 1
    with open(csv_output, "a") as out:
        for pair, count in pair_counter.items():
            out.write(f"{sample_id},{pair},{count}\n")

def process_all_samples(resfinder_dir, kraken_dir, output_dir, cov, identity):
    # Run filtering and Kraken mapping on all samples in resfinder_dir
    os.makedirs(output_dir, exist_ok=True)
    temp_dir = os.path.join(output_dir, "temp")
    os.makedirs(temp_dir, exist_ok=True)
    csv_output = os.path.join(output_dir, "Taxa_arg_pairs.csv")
    initialize_csv(csv_output)

    for sample_id in os.listdir(resfinder_dir):
        sample_path = os.path.join(resfinder_dir, sample_id)
        if not os.path.isdir(sample_path):
            continue
        temp_files, valid_genes = process_sample_step1(sample_id, resfinder_dir, cov, identity, temp_dir)
        mapping_with_kraken(sample_id, temp_files, valid_genes, kraken_dir, csv_output)
        for tf in temp_files:
            os.remove(tf)

# ---------------------------
# CLI / main
# ---------------------------

def parse_args():
    # input/output paths and coverage/identity thresholds
    parser = argparse.ArgumentParser(description = "linking annotations produced by ResFinder with taxonomic annotations generated by Kraken2 at the read level")
    parser.add_argument("-ir","--resfinder_dir", required=True, help = "ResFinder output (containing the KMA output)")
    parser.add_argument("-ik","--kraken_dir", required=True, help = "kraken2 output directory (with kraken2 reports)")
    parser.add_argument("-o","--output_dir", required=True, help= "directory for the output table")
    parser.add_argument("-cov","--coverage", type=float, default=60, help="Coverage threshold (%) (default: 60).")
    parser.add_argument("-ID","--identity", type=float, default=80, help="Identity threshold (%) (default: 80).")
    return parser.parse_args()

def main():
    # Main entry point: parse arguments and launch processing
    args = parse_args()
    process_all_samples(args.resfinder_dir, args.kraken_dir, args.output_dir, args.coverage, args.identity)

if __name__ == "__main__":
    main()

